using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LokeyLib
{
    public interface IEncryptionPadObject
    {
        // Update the key for the object and any subobjects to the given key
        void UpdateEncryption(byte[] key);
        // As above, but also update any IVs with new IVs randomly generated by rng
        void UpdateEncryption(byte[] key, IPadDataGenerator rng);
    }
}
